-- Manager single-factor confirmation path.
--
-- Additive only: two boolean columns with defaults, plus one partial unique
-- index. No DDL against patient_cases. Both columns default to false, so this
-- migration is INERT on deploy — behaviour changes only once a staff row is
-- explicitly marked is_manager = true (see prisma/rename-staff.ts).

-- AlterTable
ALTER TABLE "case_action_logs" ADD COLUMN     "single_factor" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "staff_members" ADD COLUMN     "is_manager" BOOLEAN NOT NULL DEFAULT false;

-- ---------------------------------------------------------------------------
-- HAND-WRITTEN, not generated by Prisma. Do not remove.
--
-- At most ONE staff member may be the manager. This is an AUTH invariant, not a
-- cosmetic one: a second is_manager row would be a second identity able to pass
-- the gate with the manager code alone, and nothing in the application layer
-- would notice. Enforcing it in the database means it cannot be violated by a
-- buggy script, a manual UPDATE, or a race between two concurrent writes.
--
-- A partial index is required because a plain UNIQUE on (is_manager) would also
-- permit only one row with is_manager = false — i.e. it would cap the whole
-- roster at two people. `WHERE is_manager = true` constrains only the true rows
-- and leaves any number of false ones.
--
-- Prisma's schema language cannot express a partial unique index, so this index
-- is INVISIBLE to prisma/schema.prisma. That was TESTED on Prisma 6.19 after
-- this migration was applied: `prisma migrate dev --create-only` produced an
-- empty migration, i.e. it does NOT treat the index as drift and does not
-- propose dropping it.
--
-- Still worth knowing, because that behaviour is not a documented guarantee: if
-- a future Prisma version ever generates a DROP for this index, the correct
-- response is to delete that statement, not to accept it. The comment on
-- StaffMember.isManager repeats the pointer where someone is most likely to look.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "staff_members_one_manager" ON "staff_members" ("is_manager") WHERE "is_manager" = true;
